# Site wide configuration

title: Algorithmia Developer Center
description: Resources tutorials and guides for Algorithmia.
logo: logos/AlgorithmiaLogo120x120.png # 120x120 px default image used for Twitter summary card
image: logos/AlgorithmiaLogo.png # default image used for FB summary card
teaser: logos/AlgorithmiaLogo120x120.png # 400x250 px max default teaser image used in image archive grid
locale: en_US

# URL used to generate absolute URLs in sitemap.xml, atom.xml, and for generating canonical URLs in <head>.
# When developing locally either comment this out or use something like http://localhost:4000 so all assets load properly.
# Donâ€™t include a trailing /.
url: http://developers.algorithmia.com

# For iterating on style shared with webserver,
# set this to http://localhost:9000, and edit CSS in the local webserver
webserver: https://algorithmia.com

# If you aren't editting the client guides on github,
# setting this to true can speed up hot-reloads
skip_readme_updates: false

# Jekyll configuration
sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

# Site owner
owner:
  name: Algorithmia
  email: mia@algorithmia.com
  twitter: algorithmia
  bio:
  avatar: /authors/bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname: # disabled for now. Each post can use the comments feature flag to allow or disallow commenting via diqus.

# Generate_category_page plugin configuration:
# If you change this (not recommended), you will have to update the navigation data as well.
category_dir: / # sets the root folder for where to output the category directories.

author_dir: / # sets the root folder for where to output the author pages.
emoji_dir: /images/emoji # For use with gemoji gem. See the plugin emoji.rb

project_dir: _posts/clients
project_output_dir: /clients

lunr_search:
  excludes: [atom.xml, index.html, sitemap.xml, 404.html]

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]

