# Site wide configuration

title: Algorithmia Developer Center
description: Resources tutorials and guides for Algorithmia.
logo: logos/AlgorithmiaLogo_tw.png # 120x120 px default image used for Twitter summary card
image: logos/AlgorithmiaLogo_fb.png # default image used for FB summary card
teaser: logos/AlgorithmiaLogo120x120.png # 400x250 px max default teaser image used in image archive grid
locale: en_US

# URL used to generate absolute URLs in sitemap.xml, atom.xml, and for generating canonical URLs in <head>.
# `jekyll serve` will automatically override this with "http://localhost:4000"
# Do not include a trailing /.
url: https://algorithmia.com

# The entire site is nested under this baseurl
baseurl: /developers

# Is this an enterprise (non http://algorithmia.com) site?
enterprise: false

# Set webserver where shared assets should be found (default = https://algorithmia.com)
# webserver: http://localhost:9000

collections:
  pages:
    output: true
    permalink: /:path/

# Jekyll configuration
sass:
    sass_dir: _sass
    style: compressed
kramdown:
  toc_levels: 1..2
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-last-modified-at

# Site owner
owner:
  name: Algorithmia
  email: mia@algorithmia.com
  twitter: algorithmia
  bio:
  avatar: /authors/bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname: # disabled for now. Each post can use the comments feature flag to allow or disallow commenting via diqus.

# Generate_category_page plugin configuration:
# If you change this (not recommended), you will have to update the navigation data as well.
category_dir: / # sets the root folder for where to output the category directories.

author_dir: / # sets the root folder for where to output the author pages.
emoji_dir: /images/emoji # For use with gemoji gem. See the plugin emoji.rb

project_dir: _posts/clients
project_output_dir: /clients

lunr_search:
  excludes: [atom.xml, index.html, sitemap.xml, 404.html]

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json", "shippable.yml", "_tmp", "vendor"]

